# Generated by Django 3.1.7 on 2021-03-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ادمین', help_text='اسم ادمین', max_length=100)),
                ('email', models.CharField(default='', help_text='ایمیل ادمین', max_length=100)),
                ('phone', models.CharField(default='0', help_text='شماره موبایل ادمین', max_length=20)),
                ('profile', models.ImageField(default='adminProfile/default.jpg', help_text='عکس ادمین', upload_to='adminProfile/')),
                ('password', models.TextField(default='', help_text='پسورد ادمین')),
            ],
        ),
    ]
