# Generated by Django 3.1.7 on 2021-03-27 14:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Panel', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile',
            field=models.ImageField(default='adminProfile/default.jpg', help_text='عکس ادمین', upload_to='adminProfile//%Y/%m/%d/%H/%m/%s'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('seenCount', models.IntegerField(default=0)),
                ('text', models.TextField(default='')),
                ('admin', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Panel.member')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Panel.category')),
            ],
        ),
    ]
